// @generated
// This file is @generated by prost-build.
/// IndexEntry is an entry in the index.
/// The index is sorted by key.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexEntry {
    /// Key is the key of the entry.
    #[prost(bytes="vec", tag="1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// Offset is the position of the value in bytes.
    #[prost(uint64, tag="2")]
    pub offset: u64,
    /// Size is the size of the value in bytes.
    #[prost(uint64, tag="3")]
    pub size: u64,
}
// @@protoc_insertion_point(module)
