name: Tests

on:
  push:
    branches: ['master']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['master']

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.26']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Cache tools
        uses: actions/cache@v6
        with:
          path: |
            ./.tools
          key: ${{ runner.os }}-aptre-tools-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-aptre-tools-

      - name: Vendor
        run: go mod vendor

      - name: Test Go
        run: make test

      - name: Lint Go
        run: make lint
